<div id="example" hidden="hidden">
    <div title="sphere">
-- click `?` icon for quick guide
-- click `Examples` button for complete samples
-- Press `Ctrl+S` to save and run
sphere(1);
    </div>
    <div title="diff of cube and sphere">
difference()
    color({1,0,0});
    cube({size=3,center = true});
    color({0,0,1});
    sphere({r = 2});
    </div>
    <div title="nested booleans">
-- result = (sphere - cylinder - (cube1 - cube2))

difference();
    color({1,0,0});
    sphere(1);
    color({0,1,0});
    cylinder({ r1 = 0.5, r2 = 0.5, from = {-1,0,0}, to = {1,0,0} });
    
    translate(0,1,0)
    difference()
        cube({size=1, center=true});
        cube({size={0.5, 1, 0.5}, center=true});
    </div>
    <div title="Push and pop Sample1">
color({92/255,66/255,178/255})
union();
	cube({size=3,center=true});
	push()
	  push()
		  rotate({45, 0, 0}) 
		  cube({size=3,center=true});
	  pop()
	  push()
		  rotate({0,45, 0}) 
		  cube({size=3,center=true});
	  pop()
	  push()
		  rotate({0, 0, 45}) 
		  cube({size=3,center=true});
	  pop()
	pop()

    </div>
<div title="Push and pop Sample2">
function createCube(x,y,z,r,g,b)
   push();
    color({r,g,b})
      translate({x,y,z});
      cube();
   pop();
end

push(); 
    union();
       createCube(1,0,0,0.8,0.2,0);
       createCube(4,0,0,0,0.2,0.8);
pop();
    
    </div>
    <div title="many objects">
function f(x)
    local result =  0.5 * x + 1;
    return result;
end

function g(x)
    local result ={5 * x + 20, f(x) * f(x) - 50, 0 };
    return result
end

function creatObj1(_color)
    color(_color);
    for x =-100,100,5 do
        local y = f(x);
        push()
            translate({x,y,0}) 
            cube({size=2,center=true});
        pop()
    end
end

function creatObj2(_color)
    color(_color)
    for a = -200,200,10 do
        push()
            translate({g(a / 8)[1],g(a / 8)[2],g(a / 8)[3]}) 
            sphere(2);
        pop()
    end
end
        
creatObj1({1,0,0}); 
creatObj2({0,0,1});
    </div>
    <div title="Function sample1">
union();
function creatObj(value,_color,direction)
    color(_color);
    local x = 0;
    local y = 0;
    local z = 0;
    for k = 0,9 do
        if(direction == "y")then
            y = y + value;
        elseif(direction == "z")then 
            z = z + value;
        else
            x = x + value;
        end
        push()
            translate({x,y,z}) 
            cube();
        pop()
    end
end

 creatObj(3,{1,0,0});
 creatObj(3,{0,1,0},"y");
 creatObj(3,{0,0,1},"z");
 creatObj(-3,{1,0,0});
 creatObj(-3,{0,1,0},"y");
 creatObj(-3,{0,0,1},"z");
    </div>
	<div title="Function sample2">
function creatObj(bTranslate,bScale)
    push()
        if(bTranslate) then
            translate({6,0,0});
            if(bScale) then
                scale({2,2,2});
            end
        end
      
    	color({0,0.5,1});
        difference() ;
    	color({0,0.5,1});
    	cube({size=3,center=true});
        color({0,0,1})
    	sphere(2);
    pop()
end
creatObj();
creatObj(true,true);
	</div>
<div title="Small Temple">
local pi_2 = 6.28;
scale(1/6);
union();
push();
	color("blue");
	translate({0,200,0});
	cylinder({ h = 80, r1 = 120, r2 = 0 });
pop();
for i = 0,5 do
	push();
		color("red");
		translate({math.sin(pi_2*i/6)*80, 0, math.cos(pi_2*i/6)*80});
		cylinder({ h = 200, r = 10});
	pop();		
end
difference();
push();
	color("yellow");
	difference();
	cylinder({h = 50, r = 100});
	translate({0,10,0});
	cylinder({ h = 50, r = 80 });
pop();
color("lime");
translate({100,35,0});
cube({ size = 50, center = true, });
    
    </div>
<div title="Parameterized Model ">
local bottom_length = 8;
local bottom_height = 2;
local bottom_width = 14;
local bottom_corner_radius = 2;
local bottom_hole_radius = 0.5;

local height = 15.5;
local backframe_thickness = 2;
local centerframe_thickness = 1;

local outer_radius = 3.5;
local inner_radius = 1.75;
local clinder_length = 6.5
local overflow = (outer_radius-inner_radius)*0.5

-- helper functions
-- @param zSide: [1,-1] if zSide==1, corner is positive z, -1 is negative z direction.
-- @param xSide: [1,-1] same as zSide. 
function CreateCorner(radius, height, zSide, xSide)
    push()
    color("red")
    difference()
        push()
            translate(-radius,0, -radius)
            cube({size={radius*2, height, radius*2}})
        pop()
        push()
            translate(xSide==1 and -radius*2 or 0,0, -radius)
            cube({size={radius*2, height, radius*2}})
        pop()
        push()
            translate(-radius,0, zSide==1 and -radius*2 or 0)
            cube({size={radius*2, height, radius*2}})
        pop()
        cylinder({r = radius, h=height})      
    pop()
end

-- Create the bottom of the widget
function CreateBottom()
    push()
    difference()
        push()
            translate(0, 0, -bottom_width/2)
            cube({size={bottom_length, bottom_height, bottom_width}})
        pop()
        for i=1, -1, -2 do
            push()
                translate(bottom_length - bottom_corner_radius, 0, (bottom_width/2-bottom_corner_radius)*i)
                CreateCorner(bottom_corner_radius, bottom_height, i, 1);
                cylinder({r = bottom_hole_radius, h=bottom_height})      
            pop()
        end
    pop()
end

-- create cross supporters
function CreateVerticalSupporters()
    -- back frame
    push()
        difference()
            push()
                translate(0, bottom_height, -bottom_width/2)
                cube({size={backframe_thickness, height-bottom_height-outer_radius+overflow, bottom_width}})
            pop()
            local slopeAngle = math.atan((bottom_width/2-outer_radius)/(height-bottom_height-outer_radius));

            push()
                translate(0, bottom_height, bottom_width/2)
                rotate({-slopeAngle*180/3.14, 0, 0});
                cube({size={backframe_thickness, height*2, bottom_width}})
            pop()
            push()
                translate(0, bottom_height, -bottom_width/2)
                rotate({slopeAngle*180/3.14, 0, 0});
                translate(0, 0, -bottom_width);
                cube({size={backframe_thickness, height*2, bottom_width}})
            pop()
            push()
                translate(0, height - outer_radius, 0)
                cylinder({from = {0,0,0}, to = {clinder_length,0,0}, r1 = outer_radius, r2 = outer_radius});
            pop()
    pop()
    -- center frame
    push()
        difference()
            push()
                translate(0, bottom_height, -centerframe_thickness/2)
                cube({size={bottom_length, height-bottom_height-outer_radius*2+overflow, centerframe_thickness}})
            pop()
            
            local slopeAngle = math.atan((bottom_length - clinder_length)/(height - bottom_height - outer_radius*2))
            push()
                translate(bottom_length, bottom_height, -centerframe_thickness/2)
                rotate({0,0,slopeAngle*180/3.14})
                cube({size={bottom_length, height-bottom_height, centerframe_thickness}})
            pop()
    pop()
end

function CreateCylinders()
    push()
        translate(0, height - outer_radius, 0)
        difference()
            cylinder({from = {0,0,0}, to = {clinder_length,0,0}, r1 = outer_radius, r2 = outer_radius});
            cylinder({from = {0,0,0}, to = {clinder_length,0,0}, r1 = inner_radius, r2 = inner_radius});
    pop()
end

union()
CreateBottom();
CreateVerticalSupporters();
CreateCylinders()
</div>
<div title="example slow">
--wait for a moment
color({1,0,0});
intersection();
    cube({size = 2, center = true});
    difference();
        local s = sphere({ r = 1.35, fn = 50 });
        color({0,0,1},s);
        union();
            color({0,1,0});
            cylinder({ r1 = 0.7, r2 = 0.7, from = {-1,0,0}, to = {1,0,0} });
            cylinder({ r1 = 0.7, r2 = 0.7, from = {0,-1,0}, to = {0,1,0} });
            cylinder({ r1 = 0.7, r2 = 0.7, from = {0,0,-1}, to = {0,0,1} });
</div>
</div>